added skipped counter

diff --git a/heic2jpg b/heic2jpg
--- a/heic2jpg
+++ b/heic2jpg
@@ -3,10 +3,37 @@
 # Description: This script converts all .heic format in current directory to .jpg format.
 # Dependency: imagemagick
 
+# Check if ImageMagick is installed
+if ! command -v convert &> /dev/null; then
+    echo "ImageMagick is required but not installed. Please install it first."
+    exit 1
+fi
+
 count=0
-total=$(ls -1 *.heic | wc -l)
+skipped=0
+total=$(ls -1 *.heic 2>/dev/null | wc -l)
+if [[ $total -eq 0 ]]; then
+    echo "No .heic files found in the current directory."
+    exit 0
+fi
+
 for file in *.heic; do
-	convert "$file" "${file%.heic}.jpg"
-	count=$((count+1))
-	echo "Converted file $count of $total: $file"
+    if [[ -e "${file%.heic}.jpg" ]]; then
+        echo "Skipping conversion of $file. File ${file%.heic}.jpg already exists."
+				skipped=$((skipped+1))
+        continue
+    fi
+		# Converting into HEIC
+    convert "$file" "${file%.heic}.jpg"
+    if [[ $? -ne 0 ]]; then
+        echo "Error converting file: $file"
+    else
+        count=$((count+1))
+        echo "Converted file $count of $total: $file"
+    fi
 done
+
+echo "---------------------------"
+echo "Converted files: $count"
+echo "Skipped files  : $skipped"
+echo "---------------------------"
diff --git a/jpg2heic b/jpg2heic
--- a/jpg2heic
+++ b/jpg2heic
@@ -3,12 +3,36 @@
 # Description: This script converts all .jpg format in current directory to .heic format.
 # Dependency: imagemagick
 
-count=0
-total=$(ls -1 *.jpg | wc -l)
-for file in *.jpg; do 
-	# this keeps color information, all metadata and orientation.
-	convert "$file" -define opencl:enable=true -define heif:preserve-icc=true -define heif:preserve-exif=true -define heif:preserve-orientation=true "${file%.jpg}.heic"
-	count=$((count+1))
-	echo "Converted file $count of $total: $file"
-done
+# Check if ImageMagick is installed
+if ! command -v convert &> /dev/null; then
+    echo "ImageMagick is required but not installed. Please install it first."
+    exit 1
+fi
 
+count=0
+skipped=0
+total=$(ls -1 *.jpg 2>/dev/null | wc -l)
+if [[ $total -eq 0 ]]; then
+    echo "No .jpg files found in the current directory."
+    exit 0
+fi
+
+for file in *.jpg; do
+    if [[ -e "${file%.jpg}.heic" ]]; then
+        echo "Skipping $file already exists."
+				skipped=$((skipped+1))
+        continue
+    fi
+		# Converting into JPG
+    convert "$file" "${file%.jpg}.heic"
+    if [[ $? -ne 0 ]]; then
+        echo "Error converting file: $file"
+    else
+        count=$((count+1))
+        echo "Converted file $count of $total: $file"
+    fi
+done
+echo "---------------------------"
+echo "Converted files: $count"
+echo "Skipped files  : $skipped"
+echo "---------------------------"
